version: '2'

services:

  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /tmp/
    links:
      - rabbit
    expose:
      - "8000"


  rabbit:
    image: rabbitmq:3.6.9-alpine
    hostname: rabbit
    ports:
      - "5672:5672"


  celeryworker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbit
    command: celery -A evaldas worker -l info
    restart: "on-failure"


  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbit
    command: celery -A evaldas beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
