version: '3'

services:

  django:
    build: .
    links:
      - rabbit
    ports:
      - "8000:8000"
    volumes:
      - .:/evaldas


#  rabbit:
#    image: rabbitmq:3.6.9-alpine
#    hostname: rabbit
#    ports:
#      - "5672:5672"
#
#
#  celeryworker:
#    build: .
#    depends_on:
#      - rabbit
#    command: celery -A evaldas worker -l info
#    restart: "on-failure"


#  celerybeat:
#    build: .
#    depends_on:
#      - rabbit
#    command: celery -A evaldas beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler