version: '2'

services:

  django:
    build: .
    links:
      - rabbit
    ports:
      - "8000:8000"
    volumes:
      - .:/evaldas


  rabbit:
    image: rabbitmq:3.6.9-alpine
    hostname: rabbit
    ports:
      - "5672:5672"