# Generated by Django 2.1.2 on 2018-10-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updtrends', '0002_auto_20181017_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True)),
                ('link', models.CharField(max_length=256, unique=True)),
                ('date_pub', models.DateTimeField()),
                ('trend_name', models.CharField(db_index=True, max_length=256)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('priority', models.IntegerField(max_length=1)),
            ],
        ),
    ]
