# Generated by Django 2.1.2 on 2018-10-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updtrends', '0003_actualnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualnews',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
