# Generated by Django 2.1.2 on 2018-10-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updtrends', '0004_auto_20181019_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheduleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.IntegerField()),
            ],
        ),
    ]
